config/routes.rb
Rails.application.routes.draw do
  resources :messages
    
  root "messages#index"   
  mount ActionCable.server, at: '/cable'    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
    has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
     
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :require_login    

  def index
    @messages = Message.all
    @message = current_user.messages.build  
  end

  def show
  end

  def new
    @message = current_user.messages.build
  end

  def edit
  end

  def create
    @message = current_user.messages.build(message_params)

    respond_to do |format|
      if @message.save
        ActionCable.server.broadcast 'room_channel',
                                   content:  @message.content,
                                   username: @message.user.email
        format.html { redirect_back fallback_location: root_path, notice: 'Message was successfully created.' }
      else
        format.html { redirect_back fallback_location: root_path, notice: 'Message not created!' }
      end
    end
  end

  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path, notice: 'Message was successfully destroyed.' }
    end
  end

  private
    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.require(:message).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/_header.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" method="get">Invoke!</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
      </ul>
    <ul class="nav navbar-nav navbar-right">
	<% if signed_in? %>
	  <li><a><%= current_user.email %></a></li>
	  <li><a><%= button_to "Sign out", sign_out_path, method: :delete %></a></li>
	<% else %>
          <li><a href="/sign_in"><span class="glyphicon glyphicon-log-in"></span> Sign in</a></li>
	<% end %>
    </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Invoke hh</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/header" %>
    <div class="container">
    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="alert alert-success alert-dismissible">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <div class="flash <%= key %>"><%= value %></div>
        </div>        
      <% end %>
    </div>
        <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true, remote: true) do |form| %>

  <div class="form-group">
    <%= form.text_area :content,  class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Send", class: "btn btn-default" %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<div class="container text-center" style="border: 1px solid; box-shadow: 5px 10px red;">
<h1>Messages112</h1>

  <div class="well">    
    <% @messages.each do |message| %>
        <div class="well" style="background-color: white;" id="messages">
            <div style="display: inline-block; float: left;" id="messages-table">   
              <small class="message-email"><%= message.user.email %>: </small> <em <% if message.user==current_user %>style="color: red;"<% end %>> 
            <strong class="message-content">      
                  <%= message.content %></em>
            </strong>     
            </div>
            <div style="display: inline-block; float: right;">
              <% if message.user==current_user %>
                <td><%= link_to 'Edit', edit_message_path(message), class: "btn btn-default btn-xs" %></td>
                <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
               <% end %>
              </div>    
        </div>      
    <% end %>
  </div>      
<br>

<%= render 'form', message: @message %>
</div>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>